DATASETS:
  TEST: ("voc_robot_2007_test", )
  TRAIN: ("voc_robot_2007_train",)
INPUT:
  IMAGE_SIZE: 80
MODEL:
  BACKBONE:
    NAME: mobilenet_v2
    OUT_CHANNELS: (24, 1280, 512, 256, 256, 64)
  BOX_HEAD:
    PREDICTOR: SSDLiteBoxPredictor
  NUM_CLASSES: 2
  PRIORS:
    ASPECT_RATIOS:
    - - 2
      - 3
    - - 2
      - 3
    - - 2
      - 3
    - - 2
      - 3
    - - 2
      - 3
    - - 2
      - 3
    BOXES_PER_LOCATION:
    - 6
    - 6
    - 6
    - 6
    - 6
    - 6
    FEATURE_MAPS:
    - 5
    - 3
    - 2
    - 1
    - 1
    - 1
    MAX_SIZES:
    - 105
    - 150
    - 195
    - 240
    - 285
    - 330
    MIN_SIZES:
    - 60
    - 105
    - 150
    - 195
    - 240
    - 285
    STRIDES:
    - 16
    - 32
    - 64
    - 107
    - 160
    - 320
OUTPUT_DIR: outputs/width_mult/80/0.25
SOLVER:
  BATCH_SIZE: 32
  GAMMA: 0.1
  LR: 1e-3
  LR_STEPS:
  - 80000
  - 100000
  MAX_ITER: 20500
